"""Cover letter and fit analysis agent.

The CV itself is generated by the dedicated LaTeX CV agent.
"""

from __future__ import annotations

import json

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI

from jober.core.config import get_llm
from jober.core.state import JoberState
from jober.utils.llm_helpers import strip_markdown_fences


COVER_LETTER_PROMPT = """Eres un experto en redacción de cartas de presentación.
Recibirás:
1. El perfil maestro del candidato (JSON)
2. La oferta de trabajo
3. El CV adaptado ya generado

Genera una carta de presentación en Markdown con esta estructura:

# Carta de Presentación

**[Nombre del candidato]**
[Fecha]

---

Estimado equipo de [Empresa],

[Párrafo 1: gancho y propuesta de valor]

[Párrafo 2: conexión entre experiencias concretas y requisitos del puesto]

[Párrafo 3: diferencial y cierre]

Atentamente,
**[Nombre]**

Reglas:
- Personalizada para empresa y cargo
- No inventes experiencias
- Si no cumple 100%, enfatiza lo transferible y capacidad de aprendizaje

Responde SOLO con la carta en Markdown."""


MATCH_ANALYSIS_PROMPT = """Eres un analista de fit laboral.
Recibirás:
1. El perfil maestro del candidato
2. La oferta de trabajo
3. El CV adaptado

Analiza el match entre candidato y oferta:
1. match_score: número entre 0.0 y 1.0
2. analisis_fit: texto breve (3-5 oraciones) explicando fortalezas y gaps

Responde en JSON exacto:
{"match_score": 0.85, "analisis_fit": "..."}"""


async def cv_writer_node(state: JoberState) -> dict:
    """Generate cover letter and match analysis after the CV agent."""
    llm = get_llm()
    docs = state.documentos.model_copy(deep=True)

    perfil_json = state.perfil.model_dump_json(indent=2)
    oferta_json = state.oferta.model_dump_json(indent=2)
    context = (
        f"PERFIL:\n{perfil_json}\n\n"
        f"OFERTA:\n{oferta_json}\n\n"
        f"CV_ADAPTADO_MARKDOWN:\n{docs.cv_adaptado_md}\n\n"
        f"CV_ADAPTADO_LATEX:\n{docs.cv_adaptado_tex}"
    )

    cl_resp = await _call_with_retry(llm, COVER_LETTER_PROMPT, context)
    match_resp = await _call_with_retry(llm, MATCH_ANALYSIS_PROMPT, context)
    docs.cover_letter_md = cl_resp

    try:
        match_data = json.loads(strip_markdown_fences(match_resp))
        docs.match_score = float(match_data.get("match_score", 0))
        docs.analisis_fit = match_data.get("analisis_fit", "")
    except Exception:
        docs.analisis_fit = match_resp

    return {
        "documentos": docs,
        "current_agent": "cv_writer",
        "next_step": "save_output",
    }


async def _call_with_retry(llm: ChatOpenAI, system_prompt: str, context: str, max_retries: int = 3) -> str:
    import asyncio

    for attempt in range(max_retries):
        try:
            resp = await llm.ainvoke([
                SystemMessage(content=system_prompt),
                HumanMessage(content=context),
            ])
            return resp.content
        except Exception as exc:
            if "429" in str(exc) or "rate" in str(exc).lower():
                await asyncio.sleep(5 * (attempt + 1))
                continue
            raise
    raise RuntimeError("Max retries exceeded for cover letter / fit analysis")
