"""Cover letter and fit analysis agent.

The CV itself is generated by the dedicated LaTeX CV agent.
"""

from __future__ import annotations

import json
import re
from datetime import date

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI

from jober.core.config import get_llm
from jober.core.state import JoberState
from jober.utils.llm_helpers import strip_markdown_fences


COVER_LETTER_PROMPT = """Eres un escritor senior de cover letters para roles técnicos.
Recibirás:
1. El perfil maestro del candidato (JSON)
2. La oferta de trabajo
3. El CV adaptado ya generado

Genera una cover letter profesional en Markdown, lista para enviar, con esta lógica:
- encabezado breve con nombre, email, teléfono y enlaces relevantes si existen
- fecha real
- nombre exacto de la empresa
- asunto o referencia al cargo exacto
- 3 párrafos compactos, no 4-5 bloques largos
- cierre serio y limpio

Reglas:
- Debe usar el nombre EXACTO de la empresa y el cargo EXACTO de la oferta
- Debe escribirse en el idioma indicado por `IDIOMA_DOCUMENTO`
- NO uses placeholders como [Fecha], [Empresa], [Nombre]
- No inventes experiencias
- Si no cumple 100%, enfatiza lo transferible y capacidad de aprendizaje
- Tono: seguro, técnico, sobrio, nada de frases vacías
- Longitud objetivo: 220-320 palabras
- Tiene que sonar como una carta real enviada por un candidato fuerte

Responde SOLO con la carta en Markdown."""


MATCH_ANALYSIS_PROMPT = """Eres un analista de fit laboral.
Recibirás:
1. El perfil maestro del candidato
2. La oferta de trabajo
3. El CV adaptado

Analiza el match entre candidato y oferta:
1. match_score: número entre 0.0 y 1.0
2. analisis_fit: texto breve (3-5 oraciones) explicando fortalezas y gaps

Responde en JSON exacto:
{"match_score": 0.85, "analisis_fit": "..."}"""


async def cv_writer_node(state: JoberState) -> dict:
    """Generate cover letter and match analysis after the CV agent."""
    llm = get_llm()
    docs = state.documentos.model_copy(deep=True)

    perfil_json = state.perfil.model_dump_json(indent=2)
    oferta_json = state.oferta.model_dump_json(indent=2)
    document_language = _detect_offer_language(state)
    today = date.today().strftime("%B %d, %Y")
    context = (
        f"FECHA_REAL: {today}\n\n"
        f"IDIOMA_DOCUMENTO: {document_language}\n\n"
        f"PERFIL:\n{perfil_json}\n\n"
        f"OFERTA:\n{oferta_json}\n\n"
        f"CV_ADAPTADO_MARKDOWN:\n{docs.cv_adaptado_md}\n\n"
        f"CV_ADAPTADO_LATEX:\n{docs.cv_adaptado_tex}"
    )

    cl_resp = await _call_with_retry(llm, COVER_LETTER_PROMPT, context)
    match_resp = await _call_with_retry(llm, MATCH_ANALYSIS_PROMPT, context)
    docs.cover_letter_md = _sanitize_cover_letter(cl_resp, state, today)

    try:
        match_data = json.loads(strip_markdown_fences(match_resp))
        docs.match_score = float(match_data.get("match_score", 0))
        docs.analisis_fit = match_data.get("analisis_fit", "")
    except Exception:
        docs.analisis_fit = match_resp

    return {
        "documentos": docs,
        "current_agent": "cv_writer",
        "next_step": "save_output",
    }


async def _call_with_retry(llm: ChatOpenAI, system_prompt: str, context: str, max_retries: int = 3) -> str:
    import asyncio

    for attempt in range(max_retries):
        try:
            resp = await llm.ainvoke([
                SystemMessage(content=system_prompt),
                HumanMessage(content=context),
            ])
            return resp.content
        except Exception as exc:
            if "429" in str(exc) or "rate" in str(exc).lower():
                await asyncio.sleep(5 * (attempt + 1))
                continue
            raise
    raise RuntimeError("Max retries exceeded for cover letter / fit analysis")


def _sanitize_cover_letter(text: str, state: JoberState, today: str) -> str:
    """Corrige placeholders obvios y fuerza datos reales críticos."""
    perfil = state.perfil
    oferta = state.oferta
    cleaned = text.strip()

    replacements = {
        "[Fecha]": today,
        "[FECHA]": today,
        "[Nombre]": perfil.nombre,
        "[NOMBRE]": perfil.nombre,
        "[Empresa]": oferta.empresa,
        "[EMPRESA]": oferta.empresa,
    }
    for old, new in replacements.items():
        cleaned = cleaned.replace(old, new)

    cleaned = re.sub(r"^\s*#\s+Carta de Presentación\s*", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"^\s*\*\*Carta de Presentación\*\*\s*", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"^\s*\[[^\]]+\]\s*$", "", cleaned, flags=re.MULTILINE)
    cleaned = cleaned.lstrip()

    if not re.search(re.escape(today), cleaned, re.IGNORECASE):
        header = [
            f"**{perfil.nombre}**",
            " | ".join(part for part in [perfil.email, perfil.telefono] if part),
            today,
            "",
        ]
        cleaned = "\n".join(part for part in header if part is not None) + cleaned

    cleaned = re.sub(
        r"Estimad[oa]\s+equipo\s+de\s+.*?,",
        f"Estimado equipo de {oferta.empresa},",
        cleaned,
        flags=re.IGNORECASE,
    )

    if oferta.empresa and oferta.empresa not in cleaned:
        cleaned = cleaned.replace("Estimado equipo,", f"Estimado equipo de {oferta.empresa},")

    return cleaned


def _detect_offer_language(state: JoberState) -> str:
    text = " ".join(
        [
            state.oferta.titulo or "",
            state.oferta.descripcion or "",
            " ".join(state.oferta.requisitos or []),
        ]
    ).lower()
    english_markers = [
        "engineer", "machine learning", "remote", "team", "experience", "years",
        "python", "build", "models", "production", "framework", "hiring",
    ]
    score = sum(1 for marker in english_markers if marker in text)
    return "English" if score >= 3 else "Español"
