"""Cover letter and fit analysis agent.

The CV itself is generated by the dedicated LaTeX CV agent.
"""

from __future__ import annotations

import json
import re
from datetime import date

from langchain_core.messages import HumanMessage, SystemMessage

from jober.core.config import get_llm
from jober.core.logging import logger
from jober.core.prompts import get_prompt
from jober.core.state import JoberState, view_state
from jober.utils.language_detection import detect_offer_document_language
from jober.utils.llm_helpers import ainvoke_with_retry, strip_markdown_fences


async def cv_writer_node(state: JoberState) -> dict:
    """Generate cover letter and fit analysis after the CV agent."""
    state = view_state(state)
    llm = get_llm()
    docs = state.documentos.model_copy(deep=True)

    perfil_json = state.perfil.model_dump_json(indent=2)
    oferta_json = state.oferta.model_dump_json(indent=2)
    document_language = _detect_offer_language(state)
    today = date.today().strftime("%B %d, %Y")
    context = (
        f"FECHA_REAL: {today}\n\n"
        f"IDIOMA_DOCUMENTO: {document_language}\n\n"
        f"PERFIL:\n{perfil_json}\n\n"
        f"OFERTA:\n{oferta_json}\n\n"
        f"CV_ADAPTADO_MARKDOWN:\n{docs.cv_adaptado_md}\n\n"
        f"CV_ADAPTADO_LATEX:\n{docs.cv_adaptado_tex}"
    )

    try:
        cl_resp = await _call_with_retry(
            llm,
            get_prompt("cv_writer_cover_letter"),
            context,
            "cover letter",
        )
        match_resp = await _call_with_retry(
            llm,
            get_prompt("cv_writer_match_analysis"),
            context,
            "match analysis",
        )
    except Exception as exc:
        logger.exception(
            "Document generation failed for {} at {}",
            state.oferta.empresa or "(sin empresa)",
            state.oferta.url or "(sin url)",
        )
        return {"error": f"Error generando documentos con LLM: {exc}"}

    docs.cover_letter_md = _sanitize_cover_letter(cl_resp, state, today)

    try:
        match_data = json.loads(strip_markdown_fences(match_resp))
        docs.match_score = float(match_data.get("match_score", 0))
        docs.analisis_fit = match_data.get("analisis_fit", "")
    except Exception as exc:
        logger.warning(
            "Could not parse match analysis JSON for {}: {}",
            state.oferta.url or "(sin url)",
            exc,
        )
        docs.analisis_fit = match_resp

    return {
        "documentos": docs,
        "current_agent": "cv_writer",
        "next_step": "save_output",
    }


async def _call_with_retry(llm, system_prompt: str, context: str, operation: str) -> str:
    response = await ainvoke_with_retry(
        llm,
        [
            SystemMessage(content=system_prompt),
            HumanMessage(content=context),
        ],
        operation=operation,
    )
    return str(response.content)


def _sanitize_cover_letter(text: str, state: JoberState, today: str) -> str:
    """Fix obvious placeholders and enforce critical real data."""
    state = view_state(state)
    perfil = state.perfil
    oferta = state.oferta
    cleaned = text.strip()

    replacements = {
        "[Fecha]": today,
        "[FECHA]": today,
        "[Nombre]": perfil.nombre,
        "[NOMBRE]": perfil.nombre,
        "[Empresa]": oferta.empresa,
        "[EMPRESA]": oferta.empresa,
    }
    for old, new in replacements.items():
        cleaned = cleaned.replace(old, new)

    cleaned = re.sub(r"^\s*#\s+Carta de Presentacion\s*", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"^\s*\*\*Carta de Presentacion\*\*\s*", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"^\s*\[[^\]]+\]\s*$", "", cleaned, flags=re.MULTILINE)
    cleaned = cleaned.lstrip()

    if not re.search(re.escape(today), cleaned, re.IGNORECASE):
        header = [
            f"**{perfil.nombre}**",
            " | ".join(part for part in [perfil.email, perfil.telefono] if part),
            today,
            "",
        ]
        cleaned = "\n".join(part for part in header if part is not None) + cleaned

    cleaned = re.sub(
        r"Estimad[oa]\s+equipo\s+de\s+.*?,",
        f"Estimado equipo de {oferta.empresa},",
        cleaned,
        flags=re.IGNORECASE,
    )

    if oferta.empresa and oferta.empresa not in cleaned:
        cleaned = cleaned.replace("Estimado equipo,", f"Estimado equipo de {oferta.empresa},")

    return cleaned


def _detect_offer_language(state: JoberState) -> str:
    state = view_state(state)
    return detect_offer_document_language(state.oferta)
